config/routes.rb
Rails.application.routes.draw do

  root to: "site#home"

  get '/banks', to: 'banks#new'

  get '/banks/:bank_id/inter_transfers/new', to: 'transfers#new_inter_transfers', as: 'new_bank_InterTransfer'


  resources :banks do
    resources :accounts, :transfers
  end
end

app/models/account.rb
class Account < ActiveRecord::Base
  belongs_to :bank

  validates :iban, uniqueness: true, presence: true, length: { maximum: 50 }
  validates :holder, presence: true, length: { maximum: 100 }

end

app/models/bank.rb
class Bank < ActiveRecord::Base
  has_many :accounts
  has_many :transfers

  validates :name, uniqueness: true, presence: true, length: { maximum: 250 }


end

app/models/transfer.rb
class Transfer < ActiveRecord::Base
  belongs_to :bank

  def self.search_other_banks_accounts(bank)
    @search_results = Bank.all.where('name != ?', bank.name)
  end

  def self.handle_intra_bank(bank,transfer)
    @sender_account = Account.where('iban = ?',transfer.sender).first
    @beneficiary_account = Account.where('iban = ?',transfer.beneficiary).first
    @amount_transfer = transfer.amount
    if @sender_account == @beneficiary_account
      @result = "ALERT! Sender and beneficiary most be different"
    elsif @sender_account.amount >= @amount_transfer.to_i
      @sender_account.amount = @sender_account.amount - @amount_transfer.to_i
      @sender_account.save
      @beneficiary_account.amount = @beneficiary_account.amount + @amount_transfer.to_i
      @beneficiary_account.save
      @result = "Succeed"
    else
      @result = "ALERT! Not enough Money in sender account, try a smaller amount"
    end
    ["INTRA",@result]
  end

  def self.handle_inter_bank(bank,transfer)
    @sender_account_inter = Account.where('iban = ?',transfer.sender).first
    @beneficiary_account_inter = Account.where('iban = ?',transfer.beneficiary).first
    @amount_transfer_inter = transfer.amount
    @random_num = Random.rand(1..10)

    if @sender_account_inter.amount < (@amount_transfer_inter.to_i + 5)
      @result_inter = "ALERT! Not enough Money in sender account, try a smaller amount"
    elsif @amount_transfer_inter.to_i > 1000
      @result_inter = "ALERT! this transfer exceeds the 1000€ limit for Inter-bank Transfers, try a smaller amount"
    elsif @random_num <= 3
      @result_inter = "This transfer fails for the 30% chance of failure"
    elsif @sender_account_inter.amount >= (@amount_transfer_inter.to_i + 5) && @amount_transfer_inter.to_i <= 1000 && @random_num > 3
      @sender_account_inter.amount = @sender_account_inter.amount - (@amount_transfer_inter.to_i + 5)
      @sender_account_inter.save
      @beneficiary_account_inter.amount = @beneficiary_account_inter.amount + @amount_transfer_inter.to_i
      @beneficiary_account_inter.save
      @result_inter = "Succeed"
    end
    ["INTER",@result_inter]
  end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  def index
    @bank = Bank.find(params[:bank_id])
    @accounts = @bank.accounts
  end

  def new
    @bank = Bank.find(params[:bank_id])
    @account = Account.new
  end

  def create
    @account = Account.new account_params
    @account.bank_id = params[:bank_id]
    if @account.save
      flash[:notice] = "Account created succesfully!"
      render "show"
    else
      flash[:alert] = "ALERT! Account not created"
      render 'new'
    end
  end

  def edit
    @bank = Bank.find(params[:bank_id])
    @account = Account.find(params[:id])
  end

  def update
    @account = Account.find(params[:id])
    if @account.update_attributes account_params
      @message = "Succesfully update!"
      render "show"
    else
      render "edit"
    end

  end

  def show
    @bank = Bank.find(params[:bank_id])
    @account = Account.find(params[:id])
  end

  def destroy
    @account = Account.find(params[:id])
    @account.destroy
    redirect_to bank_path(params[:bank_id])
  end

  private

  def account_params
   params.require(:account).permit(:iban, :amount, :holder)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/banks_controller.rb
class BanksController < ApplicationController

  def index
  end

  def new
    @bank = Bank.new
  end

  def create
    @bank = Bank.new bank_params
    if @bank.save
      flash[:notice] = "Bank created succesfully!"
    else
      flash[:alert] = "ALERT! Bank not created"
      render 'new'
    end
  end

  def edit
    @bank = Bank.find_by(id: params[:id])
  end

  def update
    @bank = Bank.find(params[:id])
    @accounts = @bank.accounts
    @transfers = @bank.transfers
    if @bank.update_attributes bank_params
      render 'show'
    else
      render "edit"
    end

  end

  def show
    @bank= Bank.find_by(id: params[:id])
    @accounts = @bank.accounts
    @transfers = @bank.transfers
    @intra_transfers = @transfers.where('transfer_type = ?',"Intra-bank")
    @inter_transfers = @transfers.where('transfer_type = ?',"Inter-bank")
  end

  def destroy
    @bank= Bank.find_by(id: params[:id])
    @bank.destroy
    redirect_to root_path
  end

  private

  def bank_params
    params.require(:bank).permit(:name, :address, :phone, :city, :state, :country)
  end

end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def home
    @bank = Bank.all
  end
end

app/controllers/transfers_controller.rb
class TransfersController < ApplicationController

  def new
    @bank = Bank.find(params[:bank_id])
    @transfer = Transfer.new
    flash[:alert] = @result_message
  end

  def new_inter_transfers
    @bank = Bank.find(params[:bank_id])
    @other_banks_accounts = Transfer.search_other_banks_accounts(@bank)
    @transfer = Transfer.new
    flash[:alert] = @result_message
  end

  def create
    @bank = Bank.find(params[:bank_id])
    @transfer = Transfer.new transfer_params
    @transfer.bank_id = params[:bank_id]

    if @transfer.transfer_type == 'Intra-bank'
      @result_message = Transfer.handle_intra_bank(@bank,@transfer)
    else
      @result_message = Transfer.handle_inter_bank(@bank,@transfer)
    end

    if @result_message[1] == 'Succeed' && @result_message[0] == "INTRA"
      @transfer.status = @result_message[1]
      @transfer.save
      render "show"
    elsif @result_message[1] == 'Succeed' && @result_message[0] == "INTER"
      @transfer.status = @result_message[1]
      @transfer.save
      render "show"
    elsif @result_message[1] != 'Succeed' && @result_message[0] == "INTRA"
      flash[:alert] = @result_message[1]
      render "new"
    elsif @result_message[1] != 'Succeed' && @result_message[0] == "INTER"
      flash[:alert] = @result_message[1]
      @other_banks_accounts = Transfer.search_other_banks_accounts(@bank)
      render "new_inter_transfers"
    end
  end

  def show
    @transfer = Transfer.find(params[:id])
  end

  def destroy
    @transfer = Transfer.find_by(id: params[:id])
    @transfer.destroy
    redirect_to bank_path(params[:bank_id])
  end

  private

  def transfer_params
    params.require(:transfer).permit(:sender, :beneficiary, :amount, :status, :transfer_type)
  end

end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_message
    if flash[:notice]
      display_message(flash[:notice],"notice")
    elsif flash[:alert]
      display_message(flash[:alert],"alert")
    end
  end

private

  def display_message(flash,type_class)
    content_tag :div, class: "message #{type_class}" do
      content_tag :p do
        flash
      end
    end
  end
end

app/helpers/banks_helper.rb
module BanksHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/transfers_helper.rb
module TransfersHelper
end

app/views/accounts/_form.html.erb
<%= form_for [@bank,@account] do |f| %>
  <div class="field">
  <%= f.label :iban %>
  <%= f.text_field :iban, size: 20, required: 'true' %>
  </div>
  <br>
  <div class="field">
  <%= f.label :amount %>
  <%= f.number_field :amount, size: 20 %>
  </div>
  <br>
  <div class="field">
  <%= f.label :holder %>
  <%= f.text_field :holder, size: 20, required: 'true' %>
  </div>
  <br>

  <%= f.submit 'Save' %>

<% end %>

app/views/accounts/create.html.erb
 <div class="content-section-a">
      
    <div class="container">

      <div class="error">
        <%= flash_message %>
      </div>

        <div class="row">
            <div class="col-lg-5 col-sm-12">
                <hr class="section-heading-spacer">
                <div class="clearfix"></div>
                <h2 class="section-heading">Account IBAN: <%= @account.iban%></h2>
                <p></p>
                <ul>
                  <li> <strong>IBAN:</strong> <span class="" >
                    <%= "#{@account.iban}" %></span>
                  </li>
                  <li> <strong>Amount:</strong> <span class="" >
                    <%= "#{@account.amount}" %> </span>
                  </li>
                  <li> <strong>Holder:</strong>
                    <%= "#{@account.holder}" %>
                  </li>
                  <br>
                </ul>
                <br><a href="<%= bank_path(params[:bank_id]) %>">Back to <%= @bank.name%></a>
            </div>
        </div>

    </div>
    <!-- /.container -->

</div>

app/views/accounts/edit.html.erb
 <div class="content-section-a">
      
    <div class="container">

      <div class="error">
        <%= flash_message %>
      </div>

        <div class="row">
            <div class="col-lg-5 col-sm-12">
                <hr class="section-heading-spacer">
                <div class="clearfix"></div>
                <h2 class="section-heading">Accountant IBAN: <%= @account.iban %></h2>
                <p>Here you can edit account's data</p>
                <%= render "form" %>
                <br><%= link_to("Back to Account", bank_account_path(params[:bank_id],@account.id)) %>
            </div>
        </div>

    </div>
    <!-- /.container -->

</div>

app/views/accounts/index.html.erb
 <div class="content-section-a">
      
    <div class="container">

        <div class="row">
            <div class="col-lg-5 col-sm-12">
                <hr class="section-heading-spacer">
                <div class="clearfix"></div>
                <h2 class="section-heading"><%= @bank.name%>`s accounts</h2>
                <ul>
                  <% @accounts.each_with_index do |account, index| %>
                    <li> <strong>IBAN:</strong> <%= "#{account.iban}" %></li>
                    <li> <strong>Amount:</strong> <%= "#{account.amount}" %></li>
                    <li><a href="<%= bank_account_path(params[:bank_id],account.id) %>">Show</a></li>
                    <br>
                  <% end %>
                </ul>
                <br><a href="<%= new_bank_account_path(@bank.id)%>" class="btn" >Create new Account for <%= @bank.name%></a>
            </div>
        </div>

    </div>
    <!-- /.container -->

</div>

app/views/accounts/new.html.erb
 <div class="content-section-a">
      
    <div class="container">
        <div class="row">
            <div class="col-lg-5 col-sm-12">
                <hr class="section-heading-spacer">
                <div class="clearfix"></div>
                <h2 class="section-heading">Create new Account</h2>
                <p>Here you can create a new account</p>
                <%= render "form" %>
                <br><a href="<%= bank_path(params[:bank_id]) %>">Back to <%= @bank.name%></a>
            </div>
        </div>

    </div>
    <!-- /.container -->

</div>

app/views/accounts/show.html.erb
 <div class="content-section-a">
      
    <div class="container">

      <div class="error">
        <%= @message %>
        <%= flash_message %>
      </div>

        <div class="row">
            <div class="col-lg-5 col-sm-12">
                <hr class="section-heading-spacer">
                <div class="clearfix"></div>
                <h2 class="section-heading">Account IBAN: <%= @account.iban%></h2>
                <p></p>
                <ul>
                  <li> <strong>IBAN:</strong> <span class="" >
                    <%= "#{@account.iban}" %></span>
                  </li>
                  <li> <strong>Amount:</strong> <span class="" >
                    <%= "#{@account.amount}" %> </span>
                  </li>
                  <li> <strong>Holder:</strong>
                    <%= "#{@account.holder}" %>
                  </li>
                  <br>
                </ul>
                <br><a href="<%= edit_bank_account_path(params[:bank_id],@account.id)%>" class="btn" >Edit</a>
                <br><a href="<%= bank_path(params[:bank_id]) %>">Back to bank</a>
            </div>
        </div>

    </div>
    <!-- /.container -->

</div>

app/views/banks/_form.html.erb
<%= form_for [@bank] do |f| %>
  <div class="field">
  <%= f.label :name %>
  <%= f.text_field :name, size: 20, required:'' %>
  </div>
  <br>
  <div class="field">
  <%= f.label :address %>
  <%= f.text_field :address, size: 20 %>
  </div>
  <br>
  <div class="field">
  <%= f.label :phone %>
  <%= f.text_field :phone, size: 20 %>
  </div>
  <br>
  <div class="field">
  <%= f.label :city %>
  <%= f.text_field :city, size: 20 %>
  </div>
  <br>
  <div class="field">
  <%= f.label :state %>
  <%= f.text_field :state, size: 20 %>
  </div>
  <br>
  <div class="field">
  <%= f.label :country %>
  <%= f.text_field :country, size: 20 %>
  </div>
  <br>

  <%= f.submit 'Save' %>

<% end %>

app/views/banks/create.html.erb
 <div class="content-section-a">
      
    <div class="container">

      <div class="error">
        <%= flash_message %>
      </div>

        <div class="row">
            <div class="col-lg-5 col-sm-12">
                <hr class="section-heading-spacer">
                <div class="clearfix"></div>
                <h2 class="section-heading"><%= @bank.name%></h2>
                <p>Here you can see bank's info and choose to create an account</p>
                <ul>
                  <li> <strong>Address:</strong> <span class="js-branch-name" >
                    <%= "#{@bank.address}" %></span>
                  </li>
                  <li> <strong>Phone:</strong> <span class="js-address" >
                    <%= "#{@bank.phone}" %> </span>
                  </li>
                  <li> <strong>City:</strong>
                    <%= "#{@bank.city}" %>
                  </li>
                  <li> <strong>State:</strong>
                    <%= "#{@bank.state}" %>
                  </li>
                  <li> <strong>Country:</strong>
                    <%= "#{@bank.country}" %>
                  </li>
                  <br>
                </ul>
                <a href="<%= new_bank_account_path(@bank.id)%>" class="btn" >Create Account for <%= @bank.name%></a>
            </div>
        </div>

    </div>
    <!-- /.container -->

</div>

app/views/banks/edit.html.erb
 <div class="content-section-a">
      
    <div class="container">
        <div class="row">
            <div class="col-lg-5 col-sm-12">
                <hr class="section-heading-spacer">
                <div class="clearfix"></div>
                <h2 class="section-heading">Edit <%= @bank.name %></h2>
                <p>Here you can edit bank's info</p>
                <%= render "form" %>
                <br><%= link_to("Back to Bank", bank_path(@bank.id)) %>
            </div>
        </div>

    </div>
    <!-- /.container -->

</div>

app/views/banks/index.html.erb
 <div class="content-section-a">
      
    <div class="container">
        <div class="row">
            <div class="col-lg-5 col-sm-12">
                <hr class="section-heading-spacer">
                <div class="clearfix"></div>
                <h2 class="section-heading"><%= current_bank.name%>`s accounts</h2>
                <ul>
                  <% @accounts.each_with_index do |account, index| %>
                    <li> <strong>IBAN:</strong> <%= "#{account.IBAN}" %></li>
                    <li> <strong>Amount:</strong> <%= "#{account.amount}" %></li>
                    <li><a href="<%= bank_path(current_bank,account) %>">Show</a> - <a data-method="DELETE" href="<%= bank_path(current_bank,amount) %>">Delete</a></li>
                    <br>
                  <% end %>
                </ul>
            </div>
        </div>

    </div>
    <!-- /.container -->

</div>

app/views/banks/new.html.erb
 <div class="content-section-a">
      
    <div class="container">
        <div class="row">
            <div class="col-lg-5 col-sm-6">
                <hr class="section-heading-spacer">
                <div class="clearfix"></div>
                <h2 class="section-heading">Register new Bank</h2>
                <p>Here you can create a new bank</p>
                <%= render "form" %>
            </div>
            <div class="col-lg-5 col-lg-offset-2 col-sm-6">
                <img class="img-responsive" src="https://blackrockdigital.github.io/startbootstrap-landing-page/img/ipad.png" alt="">
            </div>
        </div>

    </div>
    <!-- /.container -->

</div>

app/views/banks/show.html.erb
 <div class="content-section-a">
      
    <div class="container">

      <div class="row">
            <div class="col-lg-5 col-sm-12">
                <hr class="section-heading-spacer">
                <div class="clearfix"></div>
                <h2 class="section-heading">Bank Name: <%= @bank.name %></h2>
                <p></p>
            </div>
        </div>

      <section class="row">
          <div class="statistics2 font_2">
            <div class="col-md-3">
              <h2 class="title is-2">Info:</h2>
              <ul>
                <li> <strong>Name:</strong> <span class="js-branch-name" >
                  <%= "#{@bank.name}" %></span>
                </li>
                <li> <strong>Address:</strong> <span class="js-branch-name" >
                  <%= "#{@bank.address}" %></span>
                </li>
                <li> <strong>Phone:</strong> <span class="js-address" >
                  <%= "#{@bank.phone}" %> </span>
                </li>
                <li> <strong>City:</strong>
                  <%= "#{@bank.city}" %>
                </li>
                <li> <strong>State:</strong>
                  <%= "#{@bank.state}" %>
                </li>
                <li> <strong>Country:</strong>
                  <%= "#{@bank.country}" %>
                </li>
              </ul>
              <br>
              <a href="<%= edit_bank_path(@bank.id)%>" class="btn" >Edit Bank Info</a>
              <br>
            </div>
          </div>
          <div class="col-md-3">
            <h2 class="title is-2">Accounts:</h2>
            <a href="<%= new_bank_account_path(@bank.id)%>" class="btn" >Create Account for <%= @bank.name%></a>
            <br>
            <ul>
              <% @accounts.each_with_index do |account, index| %>
                <li> <strong>IBAN:</strong> <%= "#{account.iban}" %></li>
                <li> <strong>Amount:</strong> <%= "#{account.amount}" %></li>
                <li> <strong>Holder:</strong> <%= "#{account.holder}" %></li>
                <li><a href="<%= bank_account_path(params[:id],account.id) %>">Show</a>
                  / <%= link_to("Delete", bank_account_path(params[:id],account.id), method: :delete, data: {confirm: "Are you sure?"}) %>
                </li>
                <br>
              <% end %>
            </ul>
          </div>
          <div class="col-md-6">
            <h2 class="title is-2">History of Transfers:</h2>
            <label for="">
              <%= @intra_transfers != nil ? @intra_transfers.length : 0 %> Intra-bank Transfers
            </label>
            <br>
            <label for="">
              <%= @inter_transfers != nil ? @inter_transfers.length : 0 %> Inter-bank Transfers
            </label>
            <div class="row">
              <div class="col-md-6">
                <a href="<%= new_bank_transfer_path(params[:id])%>" class="btn" >Make Intra-bank transfer</a>
                <br>
                <ul>
                  <% if @intra_transfers != nil %>
                    <% @intra_transfers.each_with_index do |transfer, index| %>
                        <li> <strong>Sender:</strong> <%= "#{transfer.sender}" %></li>
                        <li> <strong>Beneficiary:</strong> <%= "#{transfer.beneficiary}" %></li>
                        <li> <strong>Type:</strong> <%= "#{transfer.transfer_type}" %></li>
                        <li> <strong>Amount:</strong> <%= "#{transfer.amount}" %></li>
                        <li> <strong>Status:</strong> <%= "#{transfer.status}" %></li>
                        <li><a href="<%= bank_transfer_path(params[:id],transfer.id) %>">Show</a>
                          / <%= link_to("Delete", bank_transfer_path(params[:id],transfer.id), method: :delete, data: {confirm: "Are you sure?"}) %>
                        </li>
                        <br>
                    <% end %>
                  <% end %>
                </ul>
              </div>
              <div class="col-md-6">
                <a href="<%= new_bank_InterTransfer_path(params[:id])%>" class="btn" >Make Inter-bank transfer</a>
                <br>
                <ul>
                  <% if @inter_transfers != nil %>
                    <% @inter_transfers.each_with_index do |transfer, index| %>
                        <li> <strong>Sender:</strong> <%= "#{transfer.sender}" %></li>
                        <li> <strong>Beneficiary:</strong> <%= "#{transfer.beneficiary}" %></li>
                        <li> <strong>Type:</strong> <%= "#{transfer.transfer_type}" %></li>
                        <li> <strong>Amount:</strong> <%= "#{transfer.amount}" %></li>
                        <li> <strong>Status:</strong> <%= "#{transfer.status}" %></li>
                        <li><a href="<%= bank_transfer_path(params[:id],transfer.id) %>">Show</a>
                          / <%= link_to("Delete", bank_transfer_path(params[:id],transfer.id), method: :delete, data: {confirm: "Are you sure?"}) %>
                        </li>
                        <br>
                    <% end %>
                  <% end %>
                </ul>
              </div>
            </div>
          </div>
        </section>
    </div>
    <!-- /.container -->

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Code_Test_Banking</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <link rel="icon"
      type="image/jpg"
      href="https://lh3.googleusercontent.com/-6bOtZaBgj1s/AAAAAAAAAAI/AAAAAAAABnk/BXnCWxG3QqQ/s120-p-rw-no/photo.jpg">

  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

  <!-- Custom CSS -->
    <link href="https://blackrockdigital.github.io/startbootstrap-landing-page/css/landing-page.css" rel="stylesheet">
  <!-- Custom Fonts -->
  <link href="https://blackrockdigital.github.io/startbootstrap-landing-page/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

</head>
<body>

  <!-- Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
        <div class="container topnav">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand topnav" href="https://www.linkedin.com/in/manuelfigueroaandrade">Manuel Figueroa</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="<%= root_path %>">Code Test</a>
                    </li>
                    <li>
                        <a href="<%= root_path %>#active_banks">Active banks</a>
                    </li>
                    <li>
                        <a href="<%= root_path %>#contact">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

<%= yield %>

  <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <ul class="list-inline">
                        <li>
                            <a href="<%= root_path %>">Home</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                            <a href="<%= root_path %>#code_test">Code Test</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                            <a href="<%= root_path %>#active_banks">Active banks</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                            <a href="<%= root_path %>#contact">Contact</a>
                        </li>
                    </ul>
                    <p class="copyright text-muted small">Copyright &copy; Manuel Figueroa 2016. All Rights Reserved</p>
                </div>
            </div>
        </div>
    </footer>

</body>
</html>

app/views/transfers/_formInter.html.erb
<%= form_for [@bank,@transfer] do |f| %>
  <div class="field">
  <%= f.label :sender %>
  <select name="transfer[sender]" id="transfer_sender">
    <% (@bank.accounts).each do |i| %>
      <option value="<%= i.iban %>"><%= i.iban+" ("+i.holder+")" %></option>
    <% end %>
  </select>
  </div>
  <br>
  <div class="field">
  <%= f.label :transfer_type %>
  <%= f.text_field :transfer_type, size: 20, value: 'Inter-bank', readonly: true %>
  </div>
  <br>
  <div class="field">
  <%= f.label :beneficiary %>
  (accounts of different banks)
  <select name="transfer[beneficiary]" id="transfer_beneficiary">
    <% (@other_banks_accounts).each do |i| %>
      <% (i.accounts).each do |j| %>
        <option value="<%= j.iban %>"><%= j.iban+" ("+j.holder+")" %></option>
      <% end %>
    <% end %>
  </select>

  </div>
  <br>
  <div class="field">
  <%= f.label :amount %>
  <%= f.text_field :amount, size: 20, required: true %>€
  </div>
  <br>

  <%= f.submit 'Save' %>

<% end %>

app/views/transfers/edit.html.erb
 <div class="content-section-a">
      
    <div class="container">
        <div class="row">
            <div class="col-lg-5 col-sm-12">
                <hr class="section-heading-spacer">
                <div class="clearfix"></div>
                <h2 class="section-heading">Edit: <%= @account.iban %></h2>
                <%= render "form" %>
                <br><%= link_to("Back to Account", bank_account_path(params[:bank_id],@account.id)) %>
            </div>
        </div>

    </div>
    <!-- /.container -->

</div>

app/views/transfers/index.html.erb
 <div class="content-section-a">
      
    <div class="container">
        <div class="row">
            <div class="col-lg-5 col-sm-12">
                <hr class="section-heading-spacer">
                <div class="clearfix"></div>
                <h2 class="section-heading"><%= @bank.name%>`s accounts</h2>
                <ul>
                  <% @accounts.each_with_index do |account, index| %>
                    <li> <strong>IBAN:</strong> <%= "#{account.iban}" %></li>
                    <li> <strong>Amount:</strong> <%= "#{account.amount}" %></li>
                    <li><a href="<%= bank_account_path(params[:bank_id],account.id) %>">Show</a></li>
                    <br>
                  <% end %>
                </ul>
                <br><a href="<%= new_bank_account_path(@bank.id)%>" class="btn" >Create new Account for <%= @bank.name%></a>
            </div>
        </div>

    </div>
    <!-- /.container -->

</div>